import json
import requests
import re

# List of pool names
pool_list = [
    "SCM",
    "REETG",
    "DEGAS",
    "SAGAN",
    "AZTEC",
    "000",
    "YOADA",
    "BLOXB",
    "PANL",
    "VETS",
    "NOVA",
    "OANDB",
    "QCPOL",
    "APEX",
    "CAKE",
    "BIO",
    "K9K",
    "PLKOZ",
    "ITZA",
    "RCADA",
    "ASN",
    "HEART",
    "ALOOP",
    "ADNT",
    "NOMAD",
    "RIOT",
    "1COMM",
    "BERCH",
    "SOLPI",
    "OYSTR",
    "WAT",
    "BONE",
    "FLUID",
    "ADA",
    "FRCA🍁",
    "SQRL",
    "ADRIA",
    "HAZEL",
    "ELIK",
    "BSSP2",
    "DISCO",
    "KARMA",
    "OTG",
    "DOTAR",
    "GREEN",
    "TECH",
    "DRMZ",
    "SPIDR",
    "EUSKL",
    "KNGHT",
    "ALPCH",
    "HEDGE",
    "ZEIT",
    "PRO",
    "SUDTI",
    "ECP",
    "MONAD",
    "ONE",
    "SUI",
    "ENVY",
    "METAL",
    "JORGE",
    "FEEL",
    "VLHLA",
    "AKYO",
    "8BALL",
    "HODLR",
    "ADALV",
    "LIT",
    "SANTO",
    "$VFS",
    "PFL01",
    "CLOVR",
    "SUGAR",
    "HAWAK",
    "GAIA",
    "1337",
    "HADA",
    "ANCO",
    "APOLO",
    "STKH1",
    "AUSST",
    "SEA",
    "AID1",
    "ADA-MIN",
    "MNKY",
    "TIGER",
    "SAPIO",
    "NASEC",
    "KYOTO",
    "DEV",
    "SPEC",
    "ALTZ",
    "DISCO",
    "4WARD",
    "COINZ",
    "ADAR",
    "OUROS",
    "ALFA",
    "46S",
    "BOOST",
    "LAKE",
    "ART",
    "TREE",
    "VAULT",
    "FALCO",
    "MOON1",
    "VICIS",
    "WOOF",
    "DIO",
    "TANGO",
    "FIKA",
    "CLYDE",
    "GNP1",
    "EPOCH",
    "VILAI",
    "BRAVE",
    "STOIC",
    "BBO",
    "JOEY",
    "CHAMP",
    "ABLE",
    "ARA",
    "DTDN",
    "CBFR",
    "1GURU",
    "CBFR",
    "EASY1",
    "VIET",
    "VICIS",
    "JNGL",
    "STLL",
    "BKV",
    "HAPPY",
    "FRCA🍁",
    "SHARE",
    "MOCHI",
    "8BALL",
    "LCP",
    "BIRTH",
    "AVA",
    "BRNS",
    "STPZ1",
    "RX78",
    "ANET",
    "OTAKU",
    "STAYK",
    "BANC"
]

# Make the API request
headers = {
    "User-Agent": "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Mobile Safari/537.36"
}
url = "https://js.cexplorer.io/api-static/pool/list.json"
response = requests.get(url, headers=headers)
data = response.json()

# Filter and extract relevant pool data
filtered_pools = []
for item in data['data']:
    for name in pool_list:
        pattern = r"\[{}\]".format(re.escape(name))
        if re.search(pattern, item['name']):
            filtered_pools.append(item)
            break

# Save the filtered pool data to a JSON file
with open("all-pool-list.json", "w") as file:
    json.dump(filtered_pools, file, indent=2)
